### ISSUE TITLE
fails executing du to set -o 

### ISSUE THREAD

**Issue by sjenart** [davecwright3/wsl-linux-de#1]
Under wsl2 Ubuntu 20.04 LTS new distribution,
wsl-install.sh fails while executing line 8

I needed to edit file & clear -o option to work well.

**Comment by davecwright3** [comment]
This was an error on my part. I hadn't uploaded the usage instructions (see d8993d5c91e49981fc297db324ed3ef407600acc), and in them I said to run it as `bash wsl-install.sh`. However, if you ran it as `./wsl-install.sh`, the shebang I had said to execute `/bin/sh`, but `-o pipefail` is not available in POSIX sh. I changed the shebang to `/usr/bin/env bash` in e5995e8f8299aa59e8b04718fc8c087326eac2c4, and all should be well now
